FOR-271 Update form io js binaries
qld-gov-au/formio pull request #101
Opened 2022-11-20 23:08 UTC by duttonw

formiojs@4.14.9
premium@1.19.0-rc.3

2022-11-20 23:11 UTC, duttonw commented
https://github.com/formio/enterprise-release/blob/master/API-Server-Change-Log.md#api-server-version-742
November 3rd, 2022 Release
API Server Version 7.4.2
Included Correlated Libraries:
...
formiojs@4.14.10
premium@1.19.0-rc.3
...

2022-11-20 23:42 UTC, ThrawnCA requested changes

2022-11-20 23:42 UTC, ThrawnCA commented on README.md
> +- commit and push and follow the step's to create a release.
"step's" -> "steps"

2022-11-20 23:42 UTC, ThrawnCA commented on README.md
> +- run mvn clean install (or npm intall && npm run copy-all )
"intall" -> "install"

2022-11-20 23:42 UTC, ThrawnCA commented on README.md
> +- commit and push and follow the step's to create a release.
"step's" -> "steps"

2022-11-21 00:12 UTC, ThrawnCA approved these changes

2022-11-21 00:20 UTC, merged