[QOLDEV-942] formiojs@4.21.2 premium@2.0.3 grid@1.4.0
qld-gov-au/formio pull request #759
Opened 2024-10-02 03:04 UTC by duttonw

Upgrade to align with 
## August 12, 2024 Release
### API Server Version 9.2.2
Included Correlated Libraries
* portal@9.2.1
* formiojs@4.21.2
* core@2.2.1
* vm@0.2.2
* formio@4.2.2
* premium@2.0.3
* grid@1.4.0
* formviewpro@1.108.1
* formmanager@1.106.1
* offline@4.9.1
* formio/uswds@2.5.1
* vpat@2.5.2
* reporting@1.0.3

2024-10-02 05:18 UTC, ThrawnCA requested changes
Build is broken.

2024-10-08 01:48 UTC, elvishu commented
The simpleWizard test is passing now.
I will work on fixing the next failed test (PlsPlusAddress test).

2024-10-08 03:54 UTC, ThrawnCA approved these changes

2024-10-08 03:57 UTC, ThrawnCA requested changes
Build is broken.

2024-10-09 05:52 UTC, chris-randall-qol approved these changes

2024-10-09 05:53 UTC, merged